# Action Mapping
ACTION_HOLD_OUT = 0
ACTION_BUY = 1
ACTION_SELL = 2
ACTION_CLOSE = 3
ACTION_HOLD_IN = 4

ACTION_MAP = {
    ACTION_HOLD_OUT: 'HOLD_OUT',
    ACTION_BUY: 'BUY',
    ACTION_SELL: 'SELL',
    ACTION_CLOSE: 'CLOSE',
    ACTION_HOLD_IN: 'HOLD_IN'
}
